#' Writing the spectral library into files compatible with CSI:FingerID (SIRIUS 4.0)
#'
#' The function creates a folder "CSI_FingerID" where .ms files are stored. These files can be imported to SIRIUS 4.0 software for structure elucidation. The files are named by IDs in user-defined metadata and contain at least one MS2 scan. The MS1 scan is added if available.
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#'
#' @examples
#' CSI_FingerID_writer("library_V2.mgf")
#'
#' @importFrom tools file_ext
#' @importFrom MSnbase fData readMgfData
#' @importFrom stringr str_replace_all
#' @export

CSI_FingerID_writer<-function(library, ppm_search = 20, instrument = c("qtof", "orbitrap", "fticr"), process = TRUE){

  #####################################
  ### Preparations before writing:
  #####################################

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  mainDir = getwd()
  subDir = "CSI_FingerID"

  if (file.exists(subDir)){ # If the folder already exists, remove every thing inside the folder
    setwd(file.path(mainDir, subDir))
    unlink(list.files(),force=T)
    setwd(file.path(mainDir))
  } else {  # If the folder doesn't exist, we create one
    dir.create(file.path(mainDir, subDir))
  }

  .cat <- function(..., file = con, sep = "", append = TRUE) { # Function for writing lines
    cat(..., file = file, sep = sep, append = append)
  }

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file name
    library=readMGF2(library)}

  metadata = library$metadata
  spectrum_list = library$sp

  index2=which(metadata$MSLEVEL=="2")
  metadata2 = metadata[index2,]
  ID_list=unique(metadata2$ID) # We only take IDs where MS2 data is present
  N = length(ID_list) # Number of items
  setwd(file.path(mainDir, subDir))

  ############################################
  ### Write mat file for each item in ID_list:
  ############################################

  for (i in 1:N){

    print(i)
    id=ID_list[i]
    id2=str_replace_all(id, "[^[:alnum:]]", "_")
    con <- file(description = paste0(id2,".ms"), open = "w")
    on.exit(close(con))

    index_MS1 = which(metadata$ID == id & metadata$MSLEVEL == "1")
    index_MS2 = which(metadata$ID == id & metadata$MSLEVEL == "2")

    .cat(">compound ID=",id,"\n")

    if (metadata$ADDUCT[index_MS2]=="M+H"){.cat(">ionization [M+H]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M-H"){.cat(">ionization [M-H]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Na"){.cat(">ionization [M+Na]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Cl"){.cat(">ionization [M+Cl]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+K"){.cat(">ionization [M+K]+","\n")}

    .cat(">parentmass ",metadata$PEPMASS[index_MS2],"\n")
    .cat("\n")

    if (length(index_MS1)==1){ # If MS1 data is available

      sp1=spectrum_list[[index_MS1]]
      sp1=matrix(sp1,ncol=2) # Make sure the matrix is two column

      .cat(">ms1\n")
      .cat(paste(sp1[,1]," ",sp1[,2], collapse = "\n"))
      .cat("\n")
      .cat("\n")
    }

    sp2=spectrum_list[[index_MS2]]
    sp2=matrix(sp2,ncol=2)

    .cat(">ms2\n")
    .cat(paste(sp2[,1]," ",sp2[,2], collapse = "\n"))
    .cat("\n")

  if (process){
    if (instrument=="qtof"){basic="sirius-console-64 -p qtof"}
    if (instrument=="orbitrap"){basic="sirius-console-64 -p orbitrap"}
    if (instrument=="fticr"){basic="sirius-console-64 -p fticr"}

    candidates = "-c 50"
    output = paste0("-o ",getwd(),"/dotfiles/",id2,".dot")
    #output_format = "--format dot"
    database = "-d pubchem"
    elements="-e CHNOPSCl[5]Br[5]F[5]"
    max_ppm=paste0("--ppm-max ",ppm_search)

    input=paste0(getwd(),"/",id2,".ms")

    command=paste(basic,"-F",output, candidates,database,elements, max_ppm,input,collapse = " ")
    print(command)
    system(command, timeout = 600)
   }
    #try(close(con),silent=T)
  }

  ms_files = list.files(pattern="\\.ms$")
  print(paste0(N," .ms files can be found in the folder /CSI_FingerID, and they were:"))
  print(paste(ms_files,collapse=","))

  setwd(file.path(mainDir))
}
