#' Visualize selected mass spectra in the spectral library
#'
#' The function plots all mass spectra in a library
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#' @param max.plot An integer. At least 1, maximal number of plots per page
#' @param png.out Boolean. True if plotted spectra are exported as png images!
#'
#' @examples
#' # Search library using query command lines:
#' query = library_manager(library1,query=c("IONMODE=Positive","MSLEVEL=2","RT=1.2"), logical="AND", rt_search=6)
#'
#' # Visualize scans found:
#' library_visualizer(query$SELECTED)
#'
#' @export
#'
#' @importFrom MSnbase fData readMgfData
#' @importFrom graphics plot title legend abline text
#'
library_visualizer<-function(library, max.plot=0, png.out=F){

  options(stringsAsFactors = FALSE)
  options(warn=-1)
  max_display = 5 # Display text of 5 most abundant mass peaks and higher than 5%

  #################
  ### Check inputs:
  #################

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")
  }

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)==2 & "complete" %in% names(library)){
      library = library$complete
    }
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  ##################################
  ### Reading from spectral library:
  ##################################

  if (is.character(library)){ # If input is a mgf file name
    library=readMGF2(library)}

  metadata = library$metadata
  spectrum_list = library$sp
  NI = nrow(metadata)

  if (max.plot==0){max.plot = NI}
  if (png.out){max.plot = 1}

  ##############
  ### Visualize:
  ##############

  par(mfrow=c(max.plot,1),mar=c(2,2,2,2))

  if (NI>0){

    for (i in 1:NI){

      if (png.out){png(paste0("TEMP_SCAN_",metadata$SCANS[i],".png"), width = 700, height = 480)}

      spectrum = spectrum_list[[i]]
      prec_mz = round(as.numeric(metadata$PEPMASS[i]),3)

      if (metadata$MSLEVEL[i]==1){
        xrange = c(prec_mz-2,prec_mz+8)
        ranges = which((spectrum[,1]>=prec_mz-2) & (spectrum[,1]<=prec_mz+8))
        yrange = c(10, max(spectrum[ranges,2])*1.2)}
      if (metadata$MSLEVEL[i]==2){
        xrange = c(50,prec_mz+8)
        ranges = which((spectrum[,1]>=50) & (spectrum[,1]<=prec_mz+8))
        yrange = c(10, max(spectrum[ranges,2])*1.2)}

      spectrum = spectrum[ranges,]
      if (length(ranges)==1){spectrum = matrix(spectrum, ncol=2)}

      plot(spectrum[,1],spectrum[,2], type = "h", xlim = xrange, ylim = yrange,
           xlab = "m/z", ylab = "Intensity", font.lab=2)

      kkk = min(nrow(spectrum), max_display)
      max_pics = order(spectrum[,2], decreasing = T)[1:kkk]
      max_pics = intersect(max_pics,which(spectrum[,2]>=max(spectrum[,2])*0.05))
      text_pics = spectrum[max_pics,1]
      int_pics = spectrum[max_pics,2]*1.1
      text(text_pics, int_pics, as.character(round(text_pics,3)))

      title(main = paste0("ID: ",metadata$ID[i], " ; SCAN: ", metadata$SCANS[i]),
          font = 3, cex.main = 2)
      legend("topleft", bty = "n", cex = 2, text.font = 1.5,
      #legend(xrange[1]*1.1,yrange[2]*0.95, bty = "n",
            legend = paste0(
            "Precursor: ", prec_mz,  "\n",
           #    "RT (min): ", round(as.numeric(metadata$RT[ind]),2),  "\n",
           #    "ADDUCT: ", metadata$ADDUCT[ind], "\n",
            "MS Level: ", metadata$MSLEVEL[i]))

     if (metadata$MSLEVEL[i]==2){abline(v = prec_mz, col = "red")}

     if (png.out){dev.off()}
    }} else {
     print("No scans available for ID specified!")
    }
  }

