#' Writing the spectral library into files that allow batch processing on Metfrag
#'
#' The function creates a folder "MetFrag" where .txt and .bat files are stored.
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#' @param ppm_search m/z search tolerance (in ppm) for precursor and fragments
#' @examples
#' MetFrag_writer("library_V2.mgf",ppm_search = 10)
#' @return
#' Please click on "Metfrag_batch_windows.bat" for Metfrag batch-identification!
#' @importFrom tools file_ext
#' @importFrom MSnbase fData readMgfData
#' @importFrom utils download.file
#' @importFrom stringr str_replace_all
#' @export

MetFrag_writer<-function(library,ppm_search = 20){

  #####################################
  ### Preparations before writing:
  #####################################

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  mainDir = getwd()
  subDir = "MetFrag"

  if (file.exists(subDir)){ # If the folder already exists, remove every thing inside the folder
    setwd(file.path(mainDir, subDir))
    unlink(list.files(),force=T)
    setwd(file.path(mainDir))
  } else {  # If the folder doesn't exist, we create one
    dir.create(file.path(mainDir, subDir))
  }

  .cat <- function(..., file = con, sep = "", append = TRUE) { # Function for writing lines
    cat(..., file = file, sep = sep, append = append)
  }

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file
    library=readMgfData(library, verbose = FALSE)
    metadata=fData(library)
    spectrum_list=Mgf2Splist(library)
  } else { # If input is the output of library_generator
    metadata = library$metadata
    spectrum_list = library$sp}

  index2=which(metadata$MSLEVEL=="2")
  metadata2 = metadata[index2,]
  ID_list=unique(metadata2$ID) # We only take IDs where MS2 data is present
  N = length(ID_list) # Number of items

  ###########################################
  ### Reading from parameter file template:
  ###########################################

  url = "https://github.com/daniellyz/MergeION/raw/master/inst/metfrag_template.txt"
  download.file(url,destfile="metfrag_template.txt") # Download and rename the files
  con <- file("metfrag_template.txt",open="r")
  param_lines <- readLines(con,warn = F)
  close(con)
  unlink("metfrag_template.txt") # Delete temporary parameter file

  ##############################################
  ### Write Metfrag files for each item in ID_list:
  ##############################################

  setwd(file.path(mainDir, subDir))
  url0 = "http://msbi.ipb-halle.de/~cruttkie/metfrag/MetFrag2.4.3-CL.jar"
  download.file(url0,destfile="MetFrag.jar",mode="wb") # Download and rename java file

  for (i in 1:N){

    id=ID_list[i]
    id2=str_replace_all(id, "[^[:alnum:]]", "_")

    index_MS1 = which(metadata$ID == id & metadata$MSLEVEL == "1")
    index_MS2 = which(metadata$ID == id & metadata$MSLEVEL == "2")

    #########################################
    ###  Writing MS2 spectrum data as .txt:
    #########################################

    spectrum_file = paste0(id2,"_spectrum.txt")
    spectrum=spectrum_list[[index_MS2]]
    spectrum=spectrum[order(spectrum[,1]),]
    write.table(spectrum,spectrum_file,sep="\t",dec=".",col.names = F,row.names = F)

    ##############################
    ###  Writing parameter files:
    ##############################

    param_file = paste0(id2,"_param.txt")
    param_con <- file(param_file,open="w")
    param_lines_new = param_lines

    # Write input spectrum file:

    index0 = which(grepl("PeakListPath",param_lines))
    param_lines_new[index0] = paste0("PeakListPath = ", spectrum_file)

    # Write neutral masses & precursor type:

    mz = as.numeric(metadata$PEPMASS[index_MS2])
    if (metadata$ADDUCT[index_MS2]=="M+H"){
      mzn = mz - 1.007276
      pim = 1}
    if (metadata$ADDUCT[index_MS2]=="M+Na"){
      mzn = mz - 22.989221
      pim = 23}
    if (metadata$ADDUCT[index_MS2]=="M-H"){
      mzn = mz + 1.007276
      pim = -1}
    if (metadata$ADDUCT[index_MS2]=="M+Cl"){
      mzn = mz - 34.969401
      pim = 35}
    if (metadata$ADDUCT[index_MS2]=="M+K"){
      mzn = mz - 38.963158
      pim = 39}

    index1 = which(grepl("NeutralPrecursorMass",param_lines))
    param_lines_new[index1] = paste0("NeutralPrecursorMass = ", mzn)

    index2 = which(grepl("PrecursorIonMode",param_lines))
    param_lines_new[index2] = paste0("PrecursorIonMode = ", pim)

    # Write sample name:

    index3 = which(grepl("SampleName",param_lines))
    output_name = paste0(id,"_annotated")
    param_lines_new[index3] = paste0("SampleName = ", output_name)
    output_name = paste0(output_name,".csv")

    # Write polarity:

    index4 = which(grepl("IsPositiveIonMode",param_lines))
    if (metadata$IONMODE[index_MS2]=="Negative"){
      param_lines_new[index4] = "IsPositiveIonMode = FALSE"}

    # Write ppm error:

    index5 = which(grepl("FragmentPeakMatchRelativeMassDeviation",param_lines))
    param_lines_new[index5] = paste0("FragmentPeakMatchRelativeMassDeviation = ", ppm_search)
    index6 = which(grepl("DatabaseSearchRelativeMassDeviation",param_lines))
    param_lines_new[index6] = paste0("DatabaseSearchRelativeMassDeviation = ", ppm_search)

    # Write and close the file:
    writeLines(param_lines_new,param_con)
    close(param_con)
  }

  #############################################
  ###  Writing .bat file for batch processing:
  #############################################

  param_files = list.files(pattern="\\_param.txt$")
  print(paste0(N," _param.txt files can be found in the folder /Metfrag, and they were:"))
  print(paste(param_files,collapse=","))

  bat_file = "Metfrag_batch_windows.bat"
  bat_con <- file(bat_file,open="at") # Open bat file for appending
  for (i in 1:N){
    command=paste0("java -jar MetFrag.jar ",param_files[i])
    writeLines(command,bat_con)
  }
  close(bat_con)
  setwd(file.path(mainDir))
}

############################
### Internal functions:
###########################

Mgf2Splist<-function(MGFdat){

  # From a MSnBase object to a list of spectra m/z intensity
  N=length(MGFdat)
  spectrum_list=list()
  for (i in 1:N){spectrum_list[[i]]=cbind(MGFdat[[i]]@mz,MGFdat[[i]]@intensity)}
  return(spectrum_list)
}
