#' Writing the spectral library into files compatible with MSFinder
#'
#' The function creates a folder "MSFinder" where .mat files are stored. These files can be imported to MSFinder software for structure elucidation. The files are named by IDs in user-defined metadata and contain at least one MS2 scan. The MS1 scan is added if available.
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#'
#' @examples
#' MSFinder_writer("library_V1.mgf")
#'
#' @importFrom tools file_ext
#' @importFrom MSnbase fData readMgfData
#' @importFrom stringr str_replace_all
#' @export

MSFinder_writer<-function(library, ppm_search=10, process=T){

  #####################################
  ### Preparations before writing:
  #####################################

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  mainDir = getwd()
  subDir = "MSFinder"

  if (file.exists(subDir)){ # If the folder already exists, remove every thing inside the folder
    setwd(file.path(mainDir, subDir))
    unlink(list.files(),force=T)
    setwd(file.path(mainDir))
  } else {  # If the folder doesn't exist, we create one
    dir.create(file.path(mainDir, subDir))
  }

  .cat <- function(..., file = con, sep = "", append = TRUE) { # Function for writing lines
    cat(..., file = file, sep = sep, append = append)
  }

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file name
    library=readMGF2(library)}

  metadata = library$metadata
  spectrum_list = library$sp

  index2=which(metadata$MSLEVEL=="2")
  metadata2 = metadata[index2,]
  ID_list=unique(metadata2$ID) # We only take IDs where MS2 data is present
  N = length(ID_list) # Number of items

  ###########################################
  ### Reading from parameter file template:
  ###########################################

  setwd(file.path(mainDir, subDir))
  url = "https://raw.githubusercontent.com/daniellyz/MergeION/master/inst/msfinder_template.txt"
  download.file(url,destfile="msfinder_template.txt") # Download and rename the files
  con <- file("msfinder_template.txt",open="r")
  param_lines <- readLines(con,warn = F)
  close(con)
  unlink("msfinder_template.txt") # Delete temporary parameter file

  param_con <- file("msfinder_param.txt",open="w")
  index1 = which(grepl("Ms1Tolerance=",param_lines))
  param_lines[index1] = paste0("Ms1Tolerance=", ppm_search)
  index2 = which(grepl("Ms2Tolerance=",param_lines))
  param_lines[index2] = paste0("Ms2Tolerance=", ppm_search)
  writeLines(param_lines,param_con)
  close(param_con)

  ############################################
  ### Write mat file for each item in ID_list:
  ############################################

  for (i in 1:N){

    print(i)

    id=ID_list[i]
    id2=str_replace_all(id, "[^[:alnum:]]", "_")
    con <- file(description = paste0(id2,".mat"), open = "w")
    on.exit(close(con))

    index_MS1 = which(metadata$ID == id & metadata$MSLEVEL == "1")
    index_MS2 = which(metadata$ID == id & metadata$MSLEVEL == "2")

    .cat("NAME: Compound_",i,"\n")
    .cat("PRECURSORMZ: ",metadata$PEPMASS[index_MS2],"\n")

    if (metadata$ADDUCT[index_MS2]=="M+H"){.cat("PRECURSORTYPE: [M+H]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M-H"){.cat("PRECURSORTYPE: [M-H]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Na"){.cat("PRECURSORTYPE: [M+Na]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Cl"){.cat("PRECURSORTYPE: [M+Cl]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+K"){.cat("PRECURSORTYPE: [M+K]+","\n")}

    .cat("IONMODE: ",metadata$IONMODE[index_MS2],"\n")

    if (length(index_MS1)==1){ # If MS1 data is available

      sp1=spectrum_list[[index_MS1]]
      sp1=matrix(sp1,ncol=2) # Make sure the matrix is two column

      .cat("MSTYPE: MS1\n")
      .cat("Num Peaks: ",nrow(sp1),"\n")
      .cat(paste(sp1[,1],"\t",sp1[,2], collapse = "\n"))
      .cat("\n")
    }

    sp2=spectrum_list[[index_MS2]]
    sp2=matrix(sp2,ncol=2)

    .cat("MSTYPE: MS2\n")
    .cat("Num Peaks: ",nrow(sp2),"\n")
    .cat(paste(sp2[,1],"\t",sp2[,2], collapse = "\n"))
    .cat("\n")

    if (process){
      basic = "MsfinderConsoleApp.exe predict"

      input = paste0("-i ",getwd())
      output = paste0("-o ",getwd())
      parameters = paste0("-m ",getwd(),"/msfinder_param.txt")

      command = paste(basic,input,output,parameters,collapse = " ")

      system(command, timeout = 600)
      print(command)
      unlink(paste0(id2,".mat"))
    }
}

  mat_files = list.files(pattern="\\.mat$")
  print(paste0(N," .mat files can be found in the folder /MSFinder, and they were:"))
  print(paste(mat_files,collapse=","))
  #try(close(con),silent=T)

  setwd(file.path(mainDir))
}
