#' Writing the spectral library into files compatible with MSFinder
#'
#' The function creates a folder "MSFinder" where .mat files are stored. These files can be imported to MSFinder software for structure elucidation. The files are named by IDs in user-defined metadata and contain at least one MS2 scan. The MS1 scan is added if available.
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#'
#' @examples
#' MSFinder_writer("library_V1.mgf")
#'
#' @importFrom tools file_ext
#' @importFrom MSnbase fData readMgfData
#' @export

MSFinder_writer<-function(library){

  #####################################
  ### Preparations before writing:
  #####################################

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  mainDir = getwd()
  subDir = "MSFinder"

  if (file.exists(subDir)){ # If the folder already exists, remove every thing inside the folder
    setwd(file.path(mainDir, subDir))
    unlink(list.files(),force=T)
    setwd(file.path(mainDir))
  } else {  # If the folder doesn't exist, we create one
    dir.create(file.path(mainDir, subDir))
  }

  .cat <- function(..., file = con, sep = "", append = TRUE) { # Function for writing lines
    cat(..., file = file, sep = sep, append = append)
  }

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file
    library=readMgfData(library, verbose = FALSE)
    metadata=fData(library)
    spectrum_list=Mgf2Splist(library)
  } else { # If input is the output of library_generator
    metadata = library$metadata
    spectrum_list = library$sp}

  index2=which(metadata$MSLEVEL=="2")
  metadata2 = metadata[index2,]
  ID_list=unique(metadata2$ID) # We only take IDs where MS2 data is present
  N = length(ID_list) # Number of items

  ############################################
  ### Write mat file for each item in ID_list:
  ############################################

  setwd(file.path(mainDir, subDir))

  for (i in 1:N){

    id=ID_list[i]
    con <- file(description = paste0(id,".mat"), open = "w")
    on.exit(close(con))

    index_MS1 = which(metadata$ID == id & metadata$MSLEVEL == "1")
    index_MS2 = which(metadata$ID == id & metadata$MSLEVEL == "2")

    .cat("NAME: Compound_",i,"\n")
    .cat("PRECURSORMZ: ",metadata$PEPMASS[index_MS2],"\n")

    if (metadata$ADDUCT[index_MS2]=="M+H"){.cat("PRECURSORTYPE: [M+H]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M-H"){.cat("PRECURSORTYPE: [M-H]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Na"){.cat("PRECURSORTYPE: [M+Na]+","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+Cl"){.cat("PRECURSORTYPE: [M+Cl]-","\n")}
    if (metadata$ADDUCT[index_MS2]=="M+K"){.cat("PRECURSORTYPE: [M+K]+","\n")}

    .cat("IONMODE: ",metadata$IONMODE[index_MS2],"\n")

    if (length(index_MS1)==1){ # If MS1 data is available

      sp1=spectrum_list[[index_MS1]]
      sp1=matrix(sp1,ncol=2) # Make sure the matrix is two column

      .cat("MSTYPE: MS1\n")
      .cat("Num Peaks: ",nrow(sp1),"\n")
      .cat(paste(sp1[,1],"\t",sp1[,2], collapse = "\n"))
      .cat("\n")
    }

    sp2=spectrum_list[[index_MS2]]
    sp2=matrix(sp2,ncol=2)

    .cat("MSTYPE: MS2\n")
    .cat("Num Peaks: ",nrow(sp2),"\n")
    .cat(paste(sp2[,1],"\t",sp2[,2], collapse = "\n"))
    .cat("\n")
  }

  mat_files = list.files(pattern="\\.mat$")
  print(paste0(N," .mat files can be found in the folder /MSFinder, and they were:"))
  print(paste(mat_files,collapse=","))
  #try(close(con),silent=T)

  setwd(file.path(mainDir))
}

############################
### Internal functions:
###########################

Mgf2Splist<-function(MGFdat){

  # From a MSnBase object to a list of spectra m/z intensity
  N=length(MGFdat)
  spectrum_list=list()
  for (i in 1:N){spectrum_list[[i]]=cbind(MGFdat[[i]]@mz,MGFdat[[i]]@intensity)}
  return(spectrum_list)
}
