#' For each feature (ID) extract representative scans
#'
#' The function picks a single MS1 and MS2 scan for each ID in the spectral library according to the highest TIC. It can also combine all mass spectra behind each ID into one consensus spectrum (by alignment of m/z and averaging of intensity)
#'
#' @param spectrum_list Spectra list of spectral library
#' @param metadata Metadata of spectral library
#' @param consensus  Logical. TRUE if consensus spectrum is generated by spectral alignment. FALSE if users only wish to keep the spectrum with the highest TIC.
#' @param ppm_window  m/z tolerance window (in ppm) for spectra alignment
#' @param clean Logical. TRUE if peaks not present in all spectra behind an ID are removed
#'
#' @return
#' \itemize{
#'   \item{"sp" ~ List of all extracted spectra. Each spectrum is a data matrix with two columns: m/z and intensity}
#'   \item{"metadata" ~ Data frame containing metadata of extracted scans. PEPMASS and RT are updated based on actually-detected scans. Following columns are added: FILENAME, MSLEVEL, TIC, ADDUCT, SCANNUMBER and SCANS}
#'  }
#'

process_library<-function(spectrum_list, metadata, consensus = T, ppm_window = 10, clean = T){

  new_spectrum_list = list()
  new_meta_data = c()
  NN = 0

  #######################
  ### Consensus MS1 scan:
  #######################

  index1=which(metadata$MSLEVEL==1)
  if (length(index1)>0){
    metadata1=metadata[index1,]
    ID_list=unique(metadata1$ID)
    for (ID in ID_list){
      selected_rows = which(metadata1$ID==ID)
      tics = metadata$TIC[selected_rows]
      wm = which.max(tics)
      max_scan = index1[selected_rows[wm]] # Representative scan in the old library with the highest TIC

      new_meta_data = rbind.data.frame(new_meta_data,metadata[max_scan,]) # Update metadata
      NN = NN+1
      # Append spectra list if no need for spectra merge
      if (!consensus || length(selected_rows)==1){
        new_spectrum_list[[NN]]=spectrum_list[[max_scan]]}

      # Calculate consensus spectra
      if (consensus & length(selected_rows)>1){ # If multiple spectra present we want to merge them
        splist = spectrum_list[index1[selected_rows]] # List of spectra with the same ID
        spectrum_averaged = average_spectrum(splist, ppm_window, clean)
        new_spectrum_list[[NN]] = spectrum_averaged
      }}}


  #######################
  ### Consensus MS2 scan:
  #######################

  index2=which(metadata$MSLEVEL==2)
  if (length(index2)>0){
    metadata2=metadata[index2,]
    ID_list=unique(metadata2$ID)
    for (ID in ID_list){
      selected_rows = which(metadata2$ID==ID)
      tics = metadata$TIC[selected_rows]
      wm = which.max(tics)
      max_scan = index2[selected_rows[wm]] # Representative scan in the old library with the highest TIC

      new_meta_data = rbind.data.frame(new_meta_data,metadata[max_scan,]) # Update metadata
      NN = NN+1
      # Append spectra list if no need for spectra merge
      if (!consensus || length(selected_rows)==1){
        new_spectrum_list[[NN]]=spectrum_list[[max_scan]]}

      # Calculate consensus spectra
      if (consensus & length(selected_rows)>1){ # If multiple spectra present we want to merge them
        splist = spectrum_list[index2[selected_rows]] # List of spectra with the same ID
        spectrum_averaged = average_spectrum(splist, ppm_window, clean)
        new_spectrum_list[[NN]] = spectrum_averaged
  }}}

  return(list(sp=new_spectrum_list,metadata=new_meta_data))
}
