#' Search fragments in the spectral library
#'
#' The function searches and plots all mass spectra that contain certain fragments
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#' @param fragments  Numeric vector. The m/z value(s) of query fragments.
#' @param match Character. "All" if the extracted scan must contain all query fragments; "Partial" if at least one fragment is present.
#' @param ppm_search m/z search tolerance (in ppm) for fragments
#' @return
#' \itemize{
#'  \item{"ID" ~ Vector of characters. ID(s) of metabolic feature(s) that contain query fragments.}
#'  \item{"SCANS" ~ Numeric vector. Scan number(s) that contain query fragments.}
#' }
#'
#' @examples
#' matched = match_fragments(library1,c(392.23,450.06))
#' matched = match_fragments(library1,101.06,ppm_search = 10)
#'
#' @export
#'
#' @importFrom MSnbase fData readMgfData
#' @importFrom tools file_ext
#' @importFrom graphics points
#'
match_fragments<-function(library, fragments = NULL, match = c("All","Partial"), ppm_search = 20){

  options(stringsAsFactors = FALSE)
  options(warn=-1)

  #################
  ### Check inputs:
  #################

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  if (length(fragments)==0){
    stop("Fragments to search must be a numeric value or vector!")}

  if (!is.numeric(fragments)){
   stop("Fragment m/z must be numeric!")}

  match = match.arg(match,choices=c("All","Partial"),several.ok = TRUE)

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file name
    library=readMGF2(library)}

  metadata = library$metadata
  spectrum_list = library$sp

  index2 = which(metadata$MSLEVEL=="2")
  metadata2 = metadata[index2,]
  spectrum_list2 = spectrum_list[index2]
  NN = length(index2)
  ID_found = c()
  SCANS_found = c()

  ##########################
  ### Search for fragments:
  ##########################

  for (i in 1:NN){

    spectrum = spectrum_list2[[i]]
    if (is.null(ncol(spectrum))){spectrum = matrix(spectrum,ncol=2)}

    # Remove precursor from spectra
    prec = as.numeric(metadata2$PEPMASS[i])
    prec_ind = ind_min_ppm(spectrum[,1],prec) # Precursor index

    if (ppm_distance(spectrum[prec_ind,1],prec)<ppm_search){
    spectrum2 = spectrum[-prec_ind,]} else {spectrum2 = spectrum}
    if (is.null(ncol(spectrum2))){spectrum2 = matrix(spectrum2,ncol=2)}

    # Search spectra
    mzs = spectrum2[,1]
    valid = c()
    for (fragment in fragments){
      ind = ind_min_ppm(mzs,fragment)
      if (ppm_distance(mzs[ind],fragment)<=ppm_search){
        valid=c(valid,ind)} # Save the peak that corresponds to fragment
    }

    # Plot spectra and visualize
    if ((match=="All" & length(valid)==length(fragments))
        || (match=="Partial" & length(valid)>0)){
        ID_found = c(ID_found, metadata2$ID[i])
        SCANS_found = c(SCANS_found, metadata2$SCANS[i])
        visualize.spectra(library,scan = as.numeric(metadata2$SCANS[i]))
        for (ii in valid){ # Add points to matched fragments
          points(spectrum2[ii,1],spectrum2[ii,2],pch = 19, cex = 1.2, col = "blue")}}
  }
  return(list(ID = unique(ID_found), SCANS = as.numeric(SCANS_found)))
}

############################
### Internal functions:
###########################

ind_min_ppm<-function(x,y){
  return(which.min(abs((x-y)/y*1000000)))}

ppm_distance<-function(x,y){
  return(abs((x-y)/y*1000000))}

