#' Visualize mass spectra in the spectral library
#'
#' The function plots all mass spectra of a metabolic feature
#'
#' @param library A list generated by the function library_generator() or the name of mgf spectral library file
#' @param ID  Numeric or character. The ID of metabolic feature for which mass spectra will be plotted
#' @param mslevel Must be 1 (if only MS1 scans are plotted), 2 (if only MS2 scans are plotted) or c(1,2) (if both are plotted)
#' @param scan Numeric. Scan number of the spectra plotted. ID or mslevel is not necessary if scan number is precised.
#'
#' @examples
#' visualize.spectra(library1, ID = 2, mslevel = 2)
#' visualize.spectra(library1, scan = 1)
#'
#' @export
#'
#' @importFrom MSnbase fData readMgfData
#' @importFrom graphics plot title legend abline
#' @importFrom tools file_ext
#'
visualize.spectra<-function(library, ID = NULL, mslevel=c(1,2), scan = NULL){

  options(stringsAsFactors = FALSE)
  options(warn=-1)
  max_display = 10 # Display text of 5 most abundant mass peaks

  #################
  ### Check inputs:
  #################

  if (missing(library)){
    stop("Please provide the output of library_generator() or a .mgf file as input library!")}

  if (is.character(library)){
    if (file_ext(library)!="mgf"){
      stop("The file extension of your input library must be mgf!")
    }}

  if (is.list(library)){
    if (length(library)!=2 || (!is.list(library$sp)) || !is.data.frame(library$metadata)){
      stop("Please make sure your input library is a valid output of library_generator()!")
    }}

  if (!is.character(ID)){ID = as.character(ID)}

  #####################################
  ### Reading from spectral library:
  #####################################

  if (is.character(library)){ # If input is a mgf file
    library=readMgfData(library, verbose = FALSE)
    metadata=fData(library)
    spectrum_list=Mgf2Splist(library)
  } else { # If input is the output of library_generator
    metadata = library$metadata
    spectrum_list = library$sp}

  ###########
  ### Plots:
  ###########

  if (!is.null(scan)){
    indexes = which(metadata$SCANS==scan)
  } else {
    indexes = which(metadata$ID==ID & metadata$MSLEVEL %in% mslevel)} # Scans that match to ID

  NI = length(indexes)
  if (NI>0){
  #  par(mfrow=c(NI,2))
    for (i in 1:NI){
      ind = indexes[i]
      spectrum = spectrum_list[[ind]]
      prec_mz = round(as.numeric(metadata$PEPMASS[ind]),3)
      if (metadata$MSLEVEL[ind]==1){
        xrange = c(prec_mz-5,prec_mz+10)
        yrange = NULL}
      if (metadata$MSLEVEL[ind]==2){
        xrange = c(60,prec_mz+10)
        yrange = c(0, max(spectrum[,2])*1.2)}
      plot(spectrum[,1],spectrum[,2], type = "h", xlim = xrange, ylim = yrange,
           xlab = "m/z", ylab = "Intensity", font.lab=2)

      kkk = min(length(spectrum[,1]), max_display)
      max_pics = order(spectrum[,2], decreasing = T)[1:kkk]
      text_pics = spectrum[max_pics,1]
      int_pics = spectrum[max_pics,2]*1.1
      text(text_pics, int_pics, as.character(round(text_pics,3)))

      #title(paste0("ID: ",metadata$ID[ind]))
      legend("topleft", bty = "n",
             legend = paste0(
               "Precursor: ", prec_mz,  "\n",
               "RT (min): ", round(as.numeric(metadata$RT[ind]),2),  "\n",
               "ADDUCT: ", metadata$ADDUCT[ind], "\n",
               "MS Level: ", metadata$MSLEVEL[ind]))
      if (metadata$MSLEVEL[ind]==2){abline(v = prec_mz, col = "red")}
    }} else {
     print("No scans available for ID specified!")
    }
  }

############################
### Internal functions:
###########################

Mgf2Splist<-function(MGFdat){

  # From a MSnBase object to a list of spectra m/z intensity
  N=length(MGFdat)
  spectrum_list=list()
  for (i in 1:N){spectrum_list[[i]]=cbind(MGFdat[[i]]@mz,MGFdat[[i]]@intensity)}
  return(spectrum_list)
}
